services:
  postgres:
    image: postgres:latest
    container_name: lodging_service_postgresql
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - "5433:5432"